const express = require('express');
const router = express.Router();
const pool = require('../db');
const helper = require("../lib/helpers");
var adminController = require('../controllers/adminController');
router.get("/admin", helper.isAdmin, adminController.inicio);
router.get("/admin/tablas", helper.isAdmin, adminController.tablas);
router.get("/admin/libros", helper.isAdmin, adminController.libros);
router.post("/admin/libros", helper.isAdmin, adminController.agregarLibro);
router.get("/admin/editorial", helper.isAdmin, adminController.editoriales);
router.post("/admin/editorial", helper.isAdmin, adminController.agregarEditorial);
router.get("/admin/categoria", helper.isAdmin, adminController.categorias);
router.post("/admin/categoria", helper.isAdmin, adminController.agregarCategoria);
router.get("/admin/autor", helper.isAdmin, adminController.autores);
router.post("/admin/autor", helper.isAdmin, adminController.agregarAutor);
router.get("/admin/eliminar_categoria/:id", helper.isAdmin, adminController.eliminarCategoria);
router.get("/admin/eliminar_editorial/:id", helper.isAdmin, adminController.eliminarEditorial);
router.get("/admin/eliminar_autor/:id", helper.isAdmin, adminController.eliminarAutor);
module.exports = router;