const express = require('express');
const router = express.Router();
const helper = require("../lib/helpers");
const carritoController = require('../controllers/carritoController');
router.get("/carrito/limpiar", carritoController.limpiar);
router.get("/carrito", carritoController.carrito);
router.post("/carrito/agregarlibro", carritoController.agregarLibroACarrito);
router.post("/carrito/agregarproducto", carritoController.agregarProductoACarrito);
router.post("/carrito/agregarremate", carritoController.agregarRemateACarrito);
router.get("/carrito/comprar", helper.isLogged, carritoController.compras);
router.post("/carrito/comprar", carritoController.comprar);
module.exports = router;
