const express = require('express');
const router = express.Router();
const pool = require('../db');
const helper = require("../lib/helpers");
var adminController = require('../controllers/adminController');
router.get("/admin", helper.isAdmin, adminController.inicio);
router.get("/admin/libros", helper.isAdmin, adminController.libros);
router.post("/admin/libros", helper.isAdmin, adminController.agregarLibro);
router.get("/admin/remates", helper.isAdmin, adminController.remates);
router.post("/admin/remates", helper.isAdmin, adminController.agregarRemate);
router.get("/admin/tec", helper.isAdmin, adminController.tec);
router.post("/admin/tec", helper.isAdmin, adminController.agregarTec);
router.get("/admin/editorial", helper.isAdmin, adminController.editoriales);
router.post("/admin/editorial", helper.isAdmin, adminController.agregarEditorial);
router.get("/admin/categoria", helper.isAdmin, adminController.categorias);
router.post("/admin/categoria", helper.isAdmin, adminController.agregarCategoria);
router.get("/admin/autor", helper.isAdmin, adminController.autores);
router.post("/admin/autor", helper.isAdmin, adminController.agregarAutor);
router.post("/admin/eliminar_categoria", helper.isAdmin, adminController.eliminarCategoria);
router.post("/admin/eliminar_editorial", helper.isAdmin, adminController.eliminarEditorial);
router.post("/admin/eliminar_autor", helper.isAdmin, adminController.eliminarAutor);
router.post("/admin/actualizar_categoria", helper.isAdmin, adminController.actualizarCategoria);
router.post("/admin/actualizar_editorial", helper.isAdmin, adminController.actualizarEditorial);
router.post("/admin/actualizar_autor", helper.isAdmin, adminController.actualizarAutor);
module.exports = router;